### ISSUE TITLE
Google Ad Manager Integration - Cannot read properties of undefined (reading 'price')

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-mobile-android#583] opened 2023-02-06 14:07 UTC
I have tried setting up Prebid Mobile SDK together with Google Ad Manager. They used to work.

Now I am getting these errors and the ad is not rendered:
```
I/Ads: JS: Error parsing response from cache host: SyntaxError: Unexpected token 'G', "GET /cache"... is not valid JSON (https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js:4)
I/chromium: [INFO:CONSOLE(4)] "Error parsing response from cache host: SyntaxError: Unexpected token 'G', "GET /cache"... is not valid JSON", source: https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js (4)
E/Ads: JS: Uncaught TypeError: Cannot read properties of undefined (reading 'price') (https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js:4)
I/chromium: [INFO:CONSOLE(4)] "Uncaught TypeError: Cannot read properties of undefined (reading 'price')", source: https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js (4)
```

What did I do wrong?

**Comment by YuriyVelichkoPI** [comment] 2023-02-06 14:39
Hi @clho40! We can't reproduce the issue with demo apps. Could you send us your app?

**Comment by ValentinPostindustria** [comment] 2023-02-07 14:21
Hi. Right now it works. 

But according to the logs, it looks like your creative used PUC creative (Original API), but in the code, there are Rendering API ad units. Try to check that the GAM line item uses only rendering creatives. Or try to create a new line item with only rendering creatives for testing purposes. 

[This guide](https://docs.prebid.org/adops/mobile-rendering-gam-line-item-setup.html) should help.

**Comment by YuriyVelichkoPI** [comment] 2023-02-10 11:52
@clho40 can we close this issue?

**Comment by YuriyVelichkoPI** [comment] 2023-02-23 08:40
The issue is closed since there are no updates from the reporter.

**Closed by YuriyVelichkoPI** 2023-02-23 08:40 UTC
