### ISSUE TITLE
Duplicate class a.a

### ISSUE THREAD

**Issue by MichalKapuscinski** [prebid/prebid-mobile-android#481] opened 2022-07-11 14:38 UTC
When Prebid is used with some other (also obfuscated) libraries, the build fails with error:
```
Duplicate class a.a found in modules jetified-hybid.omsdk-1.3.34-runtime (net.pubnative:hybid.omsdk:1.3.34) and jetified-prebid-mobile-sdk-open-measurement-1.3.34.1 (org.prebid:prebid-mobile-sdk-open-measurement:1.3.34.1)
Duplicate class b.a found in modules jetified-hybid.omsdk-1.3.34-runtime (net.pubnative:hybid.omsdk:1.3.34) and jetified-prebid-mobile-sdk-open-measurement-1.3.34.1 (org.prebid:prebid-mobile-sdk-open-measurement:1.3.34.1)
Duplicate class b.b found in modules jetified-hybid.omsdk-1.3.34-runtime (net.pubnative:hybid.omsdk:1.3.34) and jetified-prebid-mobile-sdk-open-measurement-1.3.34.1 (org.prebid:prebid-mobile-sdk-open-measurement:1.3.34.1)
```
etc. 

As far as I know, using `flattenpackagehierarchy` Proguard/R8 setting should help with this issue (by moving your classes to separate package).

**Comment by ValentinPostindustria** [comment] 2022-07-12 10:14
Hello. Your app tries to use the same OMSDK package from Prebid and PubNative. It's problem with Open Measurement SDK which comes to us in already compiled and obfuscated [aar-file](https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/omsdk-android/omsdk-android-1.3.34.1.aar). Even if we add `flattenpackagehierarchy` it will continue to show this error, because it's not our code.

**Comment by MichalKapuscinski** [comment] 2022-07-12 11:23
Ah, I see! Thanks a lot for pointing me in the right direction.
The older OMSDK versions (like 1.3.17 used by Prebid 2.0.0) were built properly, having all the classes in specific packages (like com.iab.omid.library.prebidorg), but now they are mixed - some in specific package, some just in a.a etc... So I'll have to wait for OMSDK fix (and Prebid updating dependency to fixed version of course), thanks :-)

**Comment by roman-tikonov** [comment] 2022-09-09 08:56
Hello folks, 

I have the same duplicate class problem with the same OMSDK version, but conflict with another obfuscated library :)
The last comment of @MichalKapuscinski is exactly on point: previous versions of OMSDK used to keep all classes in a unique root package:
<img width="343" alt="Screenshot 2022-09-09 at 10 38 44" src="https://user-images.githubusercontent.com/1324783/189312049-7278223c-9e3d-44d6-945b-e81f0e52128c.png">
But now it's just `a.a`:
<img width="361" alt="Screenshot 2022-09-09 at 10 45 15" src="https://user-images.githubusercontent.com/1324783/189312053-31653a30-b048-479a-884b-932cd041f2e8.png">

Was there a bug raised in prebid-mobile-sdk-open-measurement project? I can't find their repository / issue tracker on GitHub.

Do you know if they are already working on the fix?

**Comment by YuriyVelichkoPI** [comment] 2022-10-27 11:08
Hi @roman-tikonov @MichalKapuscinski, sorry for the long silence. We'll update omsdk to the latest version and let you know whether they fix the issue or not. 

I have an access to their slack, so if the issue is still there, I'll ask them to take a look ion it. 

I'll keep you posted.

**Comment by MichalKapuscinski** [comment] 2022-10-27 11:23
Great, thank you a lot. I've seen the same issue in many ad network SDKs, so I really hope that OMSDK finally got fixed...

**Comment by ValentinPostindustria** [comment] 2022-10-28 09:46
Hi, we checked the new OMSDK and it uses a unique classpath (`com/iab/omid/library/prebidorg/`).  So we will update OMSDK to the new version and this problem will be fixed in the new release.

**Comment by MichalKapuscinski** [comment] 2022-10-28 09:47
Awesome! Thanks for the update.

**Closed** 2022-11-08 18:27 UTC
