### ISSUE TITLE
Dr Prebid has no DFP option for Ad Server type

### ISSUE THREAD

**Issue by baneizalfe** [prebid/prebid-mobile-android#195] opened 2020-05-15 14:53 UTC
**Describe the bug**
I noticed that Dr Prebid app has no option for selecting DFP as ad server. It's manually set to `gone` in code. The PlayStore version also has DFP option missing. Why is that? iOS app has both types available. 

**To Reproduce**

**Expected behavior**
Ad Server settings should include DFP and MoPub as options.

**Screenshots**
![device-2020-05-15-165203](https://user-images.githubusercontent.com/2325003/82063954-72b23d80-96cc-11ea-8073-0c97b84ea8a0.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android Q
 - Version 10

**Comment by eros902002** [comment] 2020-05-18 15:30
Hi @baneizalfe. Thanks for the feedback.

The issue is that on iOS there's is an interceptor you can use to check all the outgoing and incoming network traffic in the app, this makes it very easy to check what the Prebid SDK is sending and what the server is responding in order to run all the required integration tests. However android does not have these features. We used some open classes from the MoPub SDK that allowed us to implement this functionality, but DFP doesn't have these, therefore we had to remove the tests for this type of integration since we cannot really validate it.

**Comment by StarWindMoonCloud** [comment] 2020-06-21 22:16
wondering if there's any update here, I was trying to play around but have the same problem

**Comment by bszekely1** [comment] 2020-09-04 22:39
The project is actively being worked on. There are a few technical limitations that we will display with a greyed out option and a dialogue box showing not supported. It should be released in the next couple of weeks.

**Closed** 2020-09-16 17:26 UTC
