### ISSUE TITLE
Audit the demo apps and SDK callbacks for memory leaks 

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-android#601] opened 2023-03-15 17:35 UTC
## Description 
The demo apps cause memory leaks. 
- We need to investigate the reasons for memory leaks. 
- Check whether the Prebid SDK callbacks may be the reason for memory leaks. 
- Update documentation with possible memory leak problems.

**Comment by ValentinPostindustria** [comment] 2023-05-11 13:57
Activities/Fragments continue to stay in memory in the demo apps even when a user leaves them. Memory leaks occur even after applying static listeners with weak references. The problem is in calling `gamAdView.loadAd(request)`. Method `gamAdView.destroy()` doesn't help. 

Demo Java App memory leaks:
![изображение](https://github.com/prebid/prebid-mobile-android/assets/72038591/96c01a4c-9abc-428c-b142-210d40afdb32)

Demo Kotlin App memory leaks:
![изображение](https://github.com/prebid/prebid-mobile-android/assets/72038591/3711ce77-ee27-49ce-b8fc-f597bc607f9a)

Internal Test App memory leaks:
![изображение](https://github.com/prebid/prebid-mobile-android/assets/72038591/36674c83-06c7-4fc7-9776-a0a5141c7ec8)

**Comment by ValentinPostindustria** [comment] 2023-05-11 15:57
# Original API investigation
### `BidLoader` outlives his Activity by at least 30 seconds. 

We need to check the auto refresh task, it can hold a reference to `BidLoader`. 

----

### Original API ad units don't have `destroy()` method that clears listeners. They only have `stopAutoRefresh()`. 

Rendering API ad units use this method, but the original API ones even don't have it. 

---

### Holding reference to Activity/Fragment with `OnCompleteListener` callback

Anonymous classes hold references to classes they called from. So if a user called this `fetchDemand()` from Activity/Fragment this anonymous class will hold a reference to Activity/Fragment. 

Code that can produce memory leak:
```
adUnit?.fetchDemand(request) {
    adView.loadAd(request)
}
```
Working solution:
```
private class MyOnCompleteListener(
    private val adRequest: AdManagerAdRequest,
    adView: AdManagerAdView,
) : OnCompleteListener {

    private val adViewReference = WeakReference(adView)

    override fun onComplete(resultCode: ResultCode?) {
        val adView = adViewReference.get()
        adView?.loadAd(adRequest)
    }
}
```

**Comment by ValentinPostindustria** [comment] 2023-05-15 13:31
### Testing example

We use the example without any GMA banners to see only our SDK's memory leaks. Some rising of memory usage after every heap dump is okay. 

Timecodes:
- 0:15 - opening the example with `BannerAdUnit`. 
- 0:20 - closing example and calling `stopAutoRefresh()`. 
- 0:30, 0:50, 1:20 - force garbage collecting and heap dump 

![изображение](https://github.com/prebid/prebid-mobile-android/assets/72038591/3c1369cf-10d0-4398-8b55-94de88e9a819)

We look at the `BidLoader` in the heap dumps. 3 possible variants:
- With `destroy()` (new, added the same as for rendering API) - it is cleared in the 3rd heap dump (1 min in memory)
- With `stopAutoRefresh()` - it is cleared in the 3rd heap dump (1 min in memory)
- Without any destroying methods - it is never cleared

So even the  `destroy()` method doesn't help to clear memory completely and immediately.

**Comment by ValentinPostindustria** [comment] 2023-05-16 08:10
After applying the fix for `BaseNetworkTask`:
- With `destroy()` it is cleared in the 1st heap dump (immediately)
- With `stopAutoRefresh()` it is cleared in the 2nd heap dump (30 seconds)
- Without any destroying methods - it is never cleared

**Comment by ValentinPostindustria** [comment] 2023-05-18 11:52
The internal test app also produces some memory leaks. It holds references to all created Bindings (they contain references to all views).
![изображение](https://github.com/prebid/prebid-mobile-android/assets/72038591/eec944ce-2b18-4e16-abcf-59ec086ff6d0)

**Comment by ValentinPostindustria** [comment] 2023-05-18 12:58
Memory usage was reduced after applying fixes to the SDK. 
In the test example, we open a lot of different examples (Original and Rendering API).

Memory usage before applying the fixes:
![Screenshot_20230518_144640](https://github.com/prebid/prebid-mobile-android/assets/72038591/4bf2d002-252d-4824-91f8-5541ba6d06e3)

Memory usage after applying the fixes:
![изображение](https://github.com/prebid/prebid-mobile-android/assets/72038591/2d309129-e6d3-4bef-885d-d914793e97e2)

**Comment by ValentinPostindustria** [comment] 2023-05-23 12:37
OM SDK also holds some references in memory, but it can be because of the memory leak produced by GMA. 
![изображение](https://github.com/prebid/prebid-mobile-android/assets/72038591/e6c5c2c3-2a27-45a7-8cb4-bb5406f35de2)

**Closed** 2023-05-24 08:24 UTC
