### ISSUE TITLE
Crash when checking UserConsentManager in Requester 

### ISSUE THREAD

**Issue by avalanchas** [prebid/prebid-mobile-android#485] opened 2022-08-10 08:37 UTC
# Description
After updating Prebid SDK from 1.12.1 to 2.0.2 I see this crash for my live users in Crashlytics
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.m()' on a null object reference
       at org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.canAccessDeviceData(UserConsentManager.java:410)
       at org.prebid.mobile.rendering.networking.modelcontrollers.Requester.getAdId(Requester.java:118)
       at org.prebid.mobile.rendering.networking.modelcontrollers.BidRequester.startAdRequest(BidRequester.java:43)
       at org.prebid.mobile.rendering.bidding.loader.BidLoader.sendBidRequest(BidLoader.java:194)
       at org.prebid.mobile.rendering.bidding.loader.BidLoader.load(BidLoader.java:145)
       at org.prebid.mobile.AdUnit.fetchDemand(AdUnit.java:157)
       at de.radio.android.ads.DisplayAdController.loadPrebid(DisplayAdController.java:182)
```

I am probably doing something wrong in the SDK initialisation, I would be very thankful for any support
```
if (!PrebidMobile.isSdkInitialized()) {
    PrebidMobile.initializeSdk(context.getApplicationContext(), null);
}
TargetingParams.setSubjectToGDPR(cmpEnabled);
BannerAdUnit bannerAdUnit = new BannerAdUnit(prebidConfigId,
        adSize.getWidth(), adSize.getHeight());
bannerAdUnit.fetchDemand(request, onCompleteListener);
```

# How to reproduce
Unclear, it seems to happen when resuming an activity, but I cannot reprroduce it locally, not even in a release build with Proguard obfuscation enabled

I can also not definitively say that Prebid 2.x is to blame, since I cannot reproduce the crash, I can also not verify that it does **not** crash on SDK < 2.x

# Tried so far
- I have checked the code for the `Requester.java` and I see that the `ManagersResolver` declares the `getUserManager()` as `@Nullable`, so ok, that is the immediate reason for the crash. But it's probably not a matter of just if-casing this. The question is why it's null at this moment
- I have read the [issue](https://github.com/prebid/prebid-mobile-android/pull/479) and the [merged code](https://github.com/prebid/prebid-mobile-android/pull/479/files) for the recent proguard changes, but none of those files mentions the `ManagersResolver` or the `UserConsentManager`. Also I have followed the Proguard docs [here](https://docs.prebid.org/prebid-mobile/legacy/android/code-integration-android.html), so I'm not convinced this is the issue
- The line that is crashing was changed during [this commit](https://github.com/prebid/prebid-mobile-android/commit/1d5dfb390e9567733a3b79dece693340f6c4aaf8) but it seems to me it would have been in danger of an NPE also before that, so I don't think this change is to blame
- I have read about the [targeting params](https://docs.prebid.org/prebid-mobile/legacy/android/targeting-params-android.html#gdpr-consent) and in my code I set `TargetingParams.setSubjectToGDPR(true)` because we use a CMP framework

# Versions / Devices
- Broad variety of devices crashes in Crashlytics, Samsung, Huawei, Sony etc.
- Android 10 and up currently visible in Crashlytics, though I suspect all versions are affected
- Prebid SDK 2.0.2

**Comment by avalanchas** [comment] 2022-08-10 13:42
Ok I have done some more digging into the code and I might have found something interesting:
In the class [StatusRequester](https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/StatusRequester.java) there is a check for the validity of the URL, line 21ff

``` 
String url = PrebidMobile.getPrebidServerHost().getHostUrl();
        if (url.contains("/openrtb2/auction")) {
```
This check is not passing for me, since I use a custom server host and the "/auction" part for me seems to belong only to Rubicon server definitions, correct?
This then stops the SDK from beind initialized correctly, and (this is a mistake on my part obviously) because I then still call `fetchDemand`, there might be some invalid internal state that can lead to the crash described in the first post of this issue

I do **not** see a check like this in the iOS code, is this a bug in the Android SDK? Does this path validation need an if-case for Appnexus vs. Rubicon vs. Custom?

**Comment by avalanchas** [comment] 2022-08-17 11:15
Maybe @ValentinPostindustria you might have an idea since you have done work in the StatusRequester class before?

**Comment by AbrahamArmasCordero** [comment] 2022-10-10 11:20
it is a bug definetly since i happend to have the same and this check even contradicts with normal hosts like APPNExus the one im using. 

Idk why are u Using 2.0.2 but you can fall back to 2.0.0 and it will be fine only lose intialization events

**Comment by YuriyVelichkoPI** [comment] 2022-10-27 10:37
Hi @avalanchas, @AbrahamArmasCordero ! Sorry for the long silence. And thank you for the detailed investigation. 

It looks like a serious bug. We'll try to put the fix in the next release.

**Comment by avalanchas** [comment] 2022-11-10 10:32
Hi, this is closed but no PR or code changes are linked?

**Comment by YuriyVelichkoPI** [comment] 2022-11-10 10:53
Hi @avalanchas ! The PR was linked to another similar ticket

https://github.com/prebid/prebid-mobile-android/pull/506

**Comment by wasaig** [comment] 2022-11-25 15:28
Hi, the crash is still happening in 2.0.4
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.l()' on a null object reference
       at org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.canAccessDeviceData(UserConsentManager.java:446)
       at org.prebid.mobile.rendering.networking.modelcontrollers.Requester.getAdId(Requester.java:118)
       at org.prebid.mobile.rendering.networking.modelcontrollers.BidRequester.startAdRequest(BidRequester.java:43)
       at org.prebid.mobile.rendering.bidding.loader.BidLoader.sendBidRequest(BidLoader.java:194)
       at org.prebid.mobile.rendering.bidding.loader.BidLoader.load(BidLoader.java:145)
       at org.prebid.mobile.AdUnit.fetchDemand(AdUnit.java:157)
```

**Comment by avalanchas** [comment] 2022-12-01 07:52
Hi Team, I'm very sorry to be so stubborn about this but I'm not sure exactly what has been fixed here. I still receive the error
```
onSdkFailedToInit: error = [Error, url doesn't contain /openrtb2/auction part]
```
at initialization even though my URL is perfectly valid with older SDK versions and I think this internally leads to the aforementioned crash later on, the NullPointer that others are also experiencing.

I read the linked ticket and the code changes and I agree that getting the TargetingParams from the Preferences looks much better now, however I don't understand how that influences this ticket here. Would be very thankful for any further insight

**Comment by YuriyVelichkoPI** [comment] 2022-12-01 08:03
Hi @wasaig, @avalanchas, 

Thanks for the reports, and sorry about the unfixed issue. We saw that as the result of incorrect initialization, the UserConsentManager was null, which led to the exception. 

But since the current bug is still here, I reopen the issue. 

For the note - we weren't able to reproduce the crash locally, so if you have a test project that reproduced the error, please, attach it to the ticket.

**Comment by MaksPetrukhnoPI** [comment] 2022-12-01 10:33
> onSdkFailedToInit: error = [Error, url doesn't contain /openrtb2/auction part]

Hi  @avalanchas 

We closed this issue because we thought that this bug was related to #492. The problem was when user migrated from 1.12.1 to 2.0.0 or newer versions (when pbGDPRSubject was boolean). As a result userConsentManager was not initialized due to ClassCastException. About your log
`onSdkFailedToInit: error = [Error, url doesn't contain /openrtb2/auction part]`
In 2.0.4 we also removed status request method from required initialization steps. This means you should see log 
`D/PrebidSdkInitializer: Prebid SDK 2.0.5 initialized`
Also I don't know how your log appears to be as onSdkFailedToInit because if your url doesn't contain openrtb2/auction you should see this log
`E/PrebidStatusRequester: Error, url doesn't contain /openrtb2/auction part`

**Comment by avalanchas** [comment] 2022-12-01 14:28
Hello Team and thanks a ton again for your fast answers!

Ok let's clarify a few things so we have no misunderstandings:
First of all I have no idea if the "erroneous" URL causes the crash, that was only ever an idea of mine, a first theory
> there might be some invalid internal state that can lead to the crash described in the first post of this issue

I am totally open for this not being the case, I still can't reproduce the crash itself, very sorry about that. 

Next: @MaksPetrukhnoPI you write
> In 2.0.4 we also removed status request method from required initialization steps. 
Maybe I have tomatoes on my eyes but in master, in tag 2.0.4, in tag 2.0.5, on the release branches, everywhere, I see line 21 and line 30 in `StatusRequester` which checks for `if (url.contains("/openrtb2/auction")) {`

As mentioned our server URL is `https://ib.adnxs.com/openrtb2/prebid` which has worked before and works on iOS. 
I mean... I'm as willing as the next guy to provide a minimal reproduction sample but I don't know how telling this will be. All I have to do in the demo apps (for instance the PrebidDemoKotlin) is to replace the Host URL with anything not containing "/openrtb2/auction" and then I get the message in the error log and no bids are loaded anymore, but yeah, we kinda knew that already, the check in the `StatusRequester` is there. But it doesn't make the crash appear in the demo app, so that remains mysterious

Oh and speaking about the error message
> Also I don't know how your log appears to be as onSdkFailedToInit 
Yeah, totally, sorry, that's my own log statement after the StatusRequester calls `onInitError` which calls `listener.onSdkFailedToInit`, so the message in the Prebid log would've been `E/PrebidStatusRequester: Error, url doesn't contain /openrtb2/auction part`, yes

**Comment by wasaig** [comment] 2022-12-01 15:38
I may be completely off here as the stack trace points to a different line but [here](https://github.com/prebid/prebid-mobile-android/blob/674d48f75171267e3b5711196f7683c9ee00a270/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java#L118) we're trying to access the instance of `UserConcentManager`, knowing that the method above `getUserConsentManager` is marked `Nullable` I assume we'd have a null check before accessing that object.

We tried but couldn't reproduce this crash on the app.

**Comment by ValentinPostindustria** [comment] 2022-12-02 10:58
Hi. 

Yes, we know that `getUserConsentManager()` can return null. And this bug can be fixed with a simple check `!= null`. But it doesn't guarantee that it will work great in the next steps. It seems that SDK isn't initialized completely and we should know the reason to fix it completely. 

Also, we found a bug that a request to `/status` continues to fail SDK initialization. But it is an optional check, that should not fail. We will fix it. 

For a better understanding of the problem:
- Have you ever get this error on 2.0.5? Because we think that it was fixed with the consent casting problem.  
- Do you call `initializeSdk()` in a separate thread? Or is it possible that SDK has not been initialized completely yet, but you have called  `fetchDemand()` already? 
- What percentage of users get this error?

**Comment by wasaig** [comment] 2022-12-02 15:17
No, we didn't try 2.0.5. We have approx 600 affected users with 5.5k crashes in just a couple of days after rollout. It's our top crash right now.

We initialize the SDK in the single thread, but there was an issue with 2.0.3 where the `initializeSdk` call would result in `onSdkFailedToInit` and `isSdkInitialized` always returned false, so we ended up passing `null` listener to the initialize call (we didn't check the behavior on 2.0.4). We asked our prebid reps about this issue and they said it's not a problem and the call to `initializeSdk()` is optional, also the documentation around the SDK setup is not clear. 

We did try to put the `initializeSdk` call in a separate thread with a 5-sec delay but couldn't reproduce the crash.

**Comment by avalanchas** [comment] 2022-12-05 11:14
> this bug can be fixed with a simple check `!= null`. But it doesn't guarantee that it will work great in the next steps. It seems that SDK isn't initialized completely and we should know the reason to fix it completely.

100% agree

> * Have you ever get this error on 2.0.5? Because we think that it was fixed with the consent casting problem.

no, not seen yet

> * Do you call `initializeSdk()` in a separate thread? Or is it possible that SDK has not been initialized completely yet, but you have called  `fetchDemand()` already?

No, not possible, cause I check on every load
```
if (!PrebidMobile.isSdkInitialized()) {
   PrebidMobile.initializeSdk(context.getApplicationContext(), new SdkInitializationListener() {
       ...
    });
}
```
Does it have to be the main thread? Should I add a Handler to check if we're on the main looper and possibly switch over?

> * What percentage of users get this error?

About 1-10%. Hard to say as this is currently in Beta and Crashlytics is very unrealiable there with the numbers

**Comment by ValentinPostindustria** [comment] 2022-12-05 17:50
Finally, we found the problem. 

### Steps to reproduce
1. Remove DemoKotlinApp from device/emulator. 
2. Checkout to `release-1.14` branch. 
3. In `CustomApplication` class for the Kotlin app after `PrebidMobile.setApplicationContext()` add `TargetingParams.setSubjectToGDPR(true)`.
4. Install and run the app.
5. Checkout to `release-2.0.3` branch.
6. Install and run any test case. 
7. Crash...

But this problem works only with 2.0.3. Crash was fixed in 2.0.4 and 2.0.5.

So please, try the SDK with the latest version. Let us know if problem still exists in the new version.

**Comment by YuriyVelichkoPI** [comment] 2022-12-05 19:22
@ValentinPostindustria let's not hurry with the diagnosis. We reopened this issue because the crash is reproduced with `2.0.4`:

https://github.com/prebid/prebid-mobile-android/issues/485#issuecomment-1327628665

**Comment by YuriyVelichkoPI** [comment] 2022-12-05 19:30
In any case, we figured out one important thing here. The publisher uses the `TargetingParams.setSubjectToGDPR(true)` in a non-appropriate way. Because of poor documentation. 

@avalanchas if you use CMP SDK in your app you shouldn't use Prebid's API to manage TCF signals. Prebid SDK will read them from the preferences automatically. The API way dedicated to providing all signals by API but not by CMP. 

I'll add a respective note to the docs for this.

**Comment by avalanchas** [comment] 2022-12-07 08:32
Hello Team, the version with 2.0.5 is now rolling out and the crash logs are coming in. The message has change to this now:
```
Exception: java.lang.NullPointerException: Attempt to read from field 'int org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.c' on a null object reference
       at org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.getRealSubjectToGdprBoolean(UserConsentManager.java:140)
       at org.prebid.mobile.rendering.sdk.deviceData.managers.UserConsentManager.canAccessDeviceData(UserConsentManager.java:233)
       at org.prebid.mobile.rendering.networking.modelcontrollers.Requester.getAdId(Requester.java:118)
       at org.prebid.mobile.rendering.networking.modelcontrollers.BidRequester.startAdRequest(BidRequester.java:43)
       at org.prebid.mobile.rendering.bidding.loader.BidLoader.sendBidRequest(BidLoader.java:194)
       at org.prebid.mobile.rendering.bidding.loader.BidLoader.load(BidLoader.java:145)
       at org.prebid.mobile.AdUnit.fetchDemand(AdUnit.java:157)
       at de.radio.android.ads.DisplayAdController.loadPrebid(DisplayAdController.java:187)
       at de.radio.android.ads.DisplayAdController.doLoadAd(DisplayAdController.java:123)
       at de.radio.android.ads.DisplayAdController.loadAd(DisplayAdController.java:100)
       at de.radio.android.appbase.ui.fragment.ads.DisplayAdFragment.loadAdIntoModule(DisplayAdFragment.java:207)
       at de.radio.android.appbase.ui.fragment.ads.DisplayAdFragment.start(DisplayAdFragment.java:193)
       at de.radio.android.appbase.ui.fragment.ads.DisplayAdFragment.onViewCreated(DisplayAdFragment.java:159)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
```
So that's very interesting! You're definitely working in the right region I would say. This `getRealSubjectToGdprBoolean` sounds to me like the error now happens further down the line but with the same basic cause?

A release **without** `TargetingParams.setSubjectToGdpr()` will be rolling out next, fingers crossed!

**Comment by wasaig** [comment] 2022-12-07 14:16
@ValentinPostindustria If you see the stactrace [here](https://github.com/prebid/prebid-mobile-android/issues/485#issuecomment-1327628665) `canAccessDeviceData` was already there before.

We don't use `TargetingParams.setSubjectToGdpr()` and still saw the crash so I don't think that's the only possible scenario for this crash.

> Yes, we know that getUserConsentManager() can return null. And this bug can be fixed with a simple check != null. But it doesn't guarantee that it will work great in the next steps. It seems that SDK isn't initialized completely and we should know the reason to fix it completely.

While I agree that we need a proper fix for this issue, the SDK shouldn't crash client apps, it should rely on logging to identify unexpected behaviors.

**Comment by YuriyVelichkoPI** [comment] 2022-12-12 20:22
@avalanchas, @wasaig, we made some changes in handling SDK's internal managers to avoid situations when one of them could be destroyed during the SDK/App lifecycle. 

Changes are introduced in release 2.0.6. We think that the crash should be fixed. Please update the SDK and let us know about the results.

**Comment by YuriyVelichkoPI** [comment] 2022-12-19 12:03
@wasaig @avalanchas, have you had a chance to update the SDK?

**Comment by avalanchas** [comment] 2022-12-20 07:46
Hi Yuri, I'm sorry we had to revert to 1.14 for now. We had a huge bug (since integrating 2.0.4) which tanked our display ad numbers and I'm still in rollback / investigation / repair mode. I don't have all the reproduction steps yet, I will come back to you on this once we're back in normal mode and relaxed from the holidays

**Comment by YuriyVelichkoPI** [comment] 2022-12-20 09:07
Hi @avalanchas. Thanks for the feedback. Yes, it totally makes sense to return to the version that doesn't harm your business. 

We'll keep this issue open until getting some feedback.

**Comment by wasaig** [comment] 2022-12-20 16:39
Hi Yuri, we also reverted to 1.12.1 when we first encountered the crash. Our release cycle also changed due to the holidays. We'll update you once we can update it back to the new version in January.

**Comment by YuriyVelichkoPI** [comment] 2023-01-26 09:49
@wasaig @avalanchas, have you had a chance to update the SDK?

**Comment by AbrahamArmasCordero** [comment] 2023-02-02 12:15
https://github.com/prebid/prebid-mobile-android/issues/485#issuecomment-1333850358
Hi im checking if this `line 30` in `StatusRequester ` Makes `Host.APPNEXUS` completly unusable 
> if (url.contains("/openrtb2/auction"))

So we want to update the sdk from `2.0.0` but we cant do it because of this

and the log now says "for now" which makes me want to ask: Is APPNEXUS going to be deprecated from now on until they Update their Server URL?

**Comment by YuriyVelichkoPI** [comment] 2023-02-02 12:34
Hi @AbrahamArmasCordero! This check doesn't influence the SDK work at all. Even if the status endpoint is unreachable, the SDK continues to work properly. 

We are going to support custom status endpoints in the next version: https://github.com/prebid/prebid-mobile-android/issues/499. 

But still, it will be an informative check. The SDK will be ready to work regardless of the status response. 

Why does it block you from updating to the latest version? (2.0.8 at this moment)

**Comment by YuriyVelichkoPI** [comment] 2023-02-02 12:39
Hm, is it an error statement problem&?

Is it treated as  "SDK doesn't support host URLs ..." `at all`? 

The wording is not the best in this case. It should say that the `status` check is not supported for custom endpoints.

**Comment by YuriyVelichkoPI** [comment] 2023-02-10 10:58
The log message will be changed in the scope of #586

**Comment by YuriyVelichkoPI** [comment] 2023-02-10 10:59
I'm closing this issue since there are no updates.

**Closed by YuriyVelichkoPI** 2023-02-10 10:59 UTC
Labels: bug, needs_docs, in progress

**Comment by avalanchas** [comment] 2023-02-15 16:44
Wow it took me way too long to return to this, so sorry

> This check doesn't influence the SDK work at all. Even if the status endpoint is unreachable, the SDK continues to work properly.

Can confirm this, works fine now, I totally misunderstood that piece of code and your posts here helped a lot. I like the new log messages, much more understandable

> Changes are introduced in release 2.0.6. We think that the crash should be fixed. Please update the SDK and let us know about the results.

I am currently starting testing with 2.0.8 and so far I cannot get it to crash locally, but yeah, I wasn't able to do that with any other versions either 😁 So that's not a definitive answer, but as you say in the answers above that you got it to be reproducible, I have a lot of faith it's fixed now.
